apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingressive-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingressive-controller.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "ingressive-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ingressive-controller.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "ingressive-controller.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INGRESSIVE_API_URL
              value: {{ .Values.api.url | quote }}
            - name: CONNECTOR_IMAGE
              value: "{{ .Values.connectorImage.repository }}:{{ .Values.connectorImage.tag }}"
            - name: INGRESS_CLASS
              value: {{ .Values.ingressClass.name | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.api.secretName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
